language: node_js
cache:
  directories:
    - node_modules # Speed up npm install
before_script:
  - npm install -g gulp
  - npm install
  - npm link
  - cd test
node_js:
  - "4"
  - "6"
  - "node"
script:
  moz build
